### ISSUE TITLE
Reverse video?

### ISSUE THREAD

**Issue by emendelson** [cracyc/msdos-player#1]
This is a wonderful project. Thank you. I have been trying to use the 486x86 version to run the WordPerfect Editor (ed.exe), which works perfectly except that the status line is not visible. It seems that msdos.exe doesn't support reverse video, or has some related problem, because ed.exe's setup/display/colors menu doesn't display the two Reverse Video options. Is there a setting that might fix this?

**Comment by cracyc** [comment]
>This is a wonderful project.

I can't take credit for it, the original is at http://takeda-toshiya.my.coocan.jp/msdos/index.html.  This fork is experimenting with WPHX virtualization and graphics in cmd windows.  I'll take a look at fixing this when I can but try the original version to see if it is correct or not.

**Comment by emendelson** [comment]
Thank you. I'll try the original version and report.

EDIT: Same problem in the original...

**Comment by cracyc** [comment]
This should be fixed (somehow with code I had in my working tree).  Note, the console window must be 80x25 and cannot be resized else the output gets messed up.

**Comment by emendelson** [comment]
Thank you for this. I booted to my old Windows 7 system and was able to build in Visual Studio 2017 with the XP-compatible toolset, but I'm not sure I got everything right. 

The new version certainly does display reverse video correctly with an 80x25 screen. When I run it with Corel's ConvertPerfect (attached), I get an "invalid psp" error message when CV exits. I have no idea what that means, and I wonder if my build is wrong. 

Here's ConvertPerfect if you're interested in testing.

[ConvertPerfect.zip](https://github.com/cracyc/msdos-player/files/4251091/ConvertPerfect.zip)

Thank you again for your trouble over this!

EDIT: Apologies for the mistaken Close - I hit the wrong button.

**Comment by cracyc** [comment]
Top of tree should fix the error.  It's mostly harmless except it would prevent resetting of the window title.

**Comment by emendelson** [comment]
Thank you - I'll build again when I'm back at my Windows 7 machine.

**Comment by emendelson** [comment]
Yes, this fixes the error message. Thank you!
