### ISSUE TITLE
Add upstream changes?

### ISSUE THREAD

**Issue by emendelson** [cracyc/msdos-player#10]
The upstream version of this project seems to have new changes:

http://takeda-toshiya.my.coocan.jp/msdos/index.html

Is it possible to incorporate them in here? 

Many thanks for your terrific work.

**Comment by cracyc** [comment]
Upstream has diverged quite a bit so it'll be some work.  I'll leave this open as a reminder that it needs to be on my to do list.

**Comment by johnsonjh** [comment]
I might take a look at this too.

**Comment by roytam1** [comment]
there were lots of changes since 2019-10-22: https://github.com/roytam1/msdos-player/compare/38be99b5953b9ef105e3a51de9d3ceb7fe052f5e...HEAD

**Comment by cracyc** [comment]
With Microsoft pushing everything to the terminal which can't host graphics like the old console could and the eventual shift to x86s which will make dos virtualization impossible, the experiments that I was doing with this fork are going to stop working.  Any further work here will likely involve throwing away much of the large differences from upstream.

**Comment by roytam1** [comment]
> can't host graphics like the old console could

you may end-up using external GDI or SDL display for graphics.

**Comment by roytam1** [comment]
and I tried to rebase some of your changes onto latest msdos-player sources: https://github.com/roytam1/msdos-player/tree/cracyc-fixes

**Comment by cracyc** [comment]
I've abandoned the old main branch it's diverged so far from upstream and as described above the experiments are a dead end so this is effectively resolved.
