### ISSUE TITLE
Running a bat file

### ISSUE THREAD

**Issue by WolfeComputerServices** [cracyc/msdos-player#12]
Why isn't msdos able to execute a BAT file? If I issue the command:

`c:\msdos -c c:\path\mybat.bat`

it returns a message of `Specify command file with extension (.COM or .EXE)`

Am I doing something wrong?

**Comment by cracyc** [comment]
There's no builtin command.com.  You can get freecom from https://github.com/FDOS/freecom/releases/tag/com085a .
