### ISSUE TITLE
MS EDIT.EXE doesn't work well

### ISSUE THREAD

**Issue by roytam1** [cracyc/msdos-player#17]
It hits invalid opcode when you try to type in main text area.
And if you try to use Menu(by activate by Alt key), it hangs.
[edit.zip](https://github.com/cracyc/msdos-player/files/14450062/edit.zip)

EDIT: found the root of issue: EDIT doesn't like columns > 80.

**Comment by cracyc** [comment]
There's nothing that can be done about that except using -n to force 80 columns.
