### ISSUE TITLE
User-configurable FILES= ?

### ISSUE THREAD

**Issue by emendelson** [cracyc/msdos-player#2]
I think I see a max files setting in the code that works like FILES= in config.sys, but is it possible that there could be a way to set FILES=100 (or whatever) without modifying the code and building? Perhaps a command-line option? If it's already there and I simply haven't seen it, then I apologize for wasting bandwidth.

**Comment by cracyc** [comment]
There's a lot of places where 20 files is hard coded.  I don't really want to mess with it unless it really becomes a big issue.

**Comment by emendelson** [comment]
Yes - I already tried messing with it, but saw that the hard-coding was something I wouldn't know how to deal with.
