### ISSUE TITLE
Appveyor page?

### ISSUE THREAD

**Issue by emendelson** [cracyc/msdos-player#4]
I realize that I'm being lazy in asking this, but (at the moment) I need to boot into an old Windows 7 system in order to build msdos-player. (As far as I can tell I would need to have VS2015 or some other older version installed in addition to VS 2019.) Is there any chance that an appveyor system could be set up for this project, so that we could download current versions without building?

Ignore me if this is more trouble than it's worth.

**Comment by cracyc** [comment]
I'll look at it when I have a chance but I build it myself with mingw.  Just use "make -f Makefile.mingw".  Put i86, i286, i386, i486 or whpx after to choose a particular version.  The whpx version requires Windows 10, Windows Hypervisor Platform and winhvplatform.h and winhvplatformdefs.h in the include path (it doesn't build with msvc currently).

**Comment by emendelson** [comment]
I should have figured that out for myself. Thank you. Will experiment this weekend.

**Comment by emendelson** [comment]
It seems that my MinGW setup isn't working correctly, because I get "can't find file" errors for files that exist in the setup. I'll fuss with this some more, but I won't ask anyone to waste time on me...
