### ISSUE TITLE
Latest commit won't build in VS 2015

### ISSUE THREAD

**Issue by emendelson** [cracyc/msdos-player#5]
I still haven't figured out how to build this project in MinGW, so I've been using VS 2015 under 32-bit Windows 7.
The latest commit (Ctrl-F10 cursor capture) won't build in VS 2015 because of many undeclared identifiers: RAWINPUTDEVICE, Rid, RIDEV_INPUTSINK, etc. 

Here's the full error report (I've left out some warnings at the end:

> 1>msdos.cpp(2782): error C2065: 'RAWINPUTDEVICE': undeclared identifier
1>msdos.cpp(2782): error C2146: syntax error: missing ';' before identifier 'Rid'
1>msdos.cpp(2782): error C2065: 'Rid': undeclared identifier
1>msdos.cpp(2783): error C2065: 'Rid': undeclared identifier
1>msdos.cpp(2783): error C2228: left of '.usUsagePage' must have class/struct/union
1>msdos.cpp(2784): error C2065: 'Rid': undeclared identifier
1>msdos.cpp(2784): error C2228: left of '.usUsage' must have class/struct/union
1>msdos.cpp(2790): error C2065: 'Rid': undeclared identifier
1>msdos.cpp(2790): error C2228: left of '.dwFlags' must have class/struct/union
1>msdos.cpp(2790): error C2065: 'RIDEV_INPUTSINK': undeclared identifier
1>msdos.cpp(2791): error C2065: 'Rid': undeclared identifier
1>msdos.cpp(2791): error C2228: left of '.hwndTarget' must have class/struct/union
1>msdos.cpp(2795): error C2065: 'Rid': undeclared identifier
1>msdos.cpp(2795): error C2228: left of '.dwFlags' must have class/struct/union
1>msdos.cpp(2795): error C2065: 'RIDEV_REMOVE': undeclared identifier
1>msdos.cpp(2796): error C2065: 'Rid': undeclared identifier
1>msdos.cpp(2796): error C2228: left of '.hwndTarget' must have class/struct/union
1>msdos.cpp(2799): error C2065: 'Rid': undeclared identifier
1>msdos.cpp(2799): error C3861: 'RegisterRawInputDevices': identifier not found
1>msdos.cpp(2811): error C2065: 'WM_INPUT': undeclared identifier
1>msdos.cpp(2811): error C2131: expression did not evaluate to a constant
1>  msdos.cpp(2811): note: failure was caused by non-constant arguments or reference to a non-constant symbol
1>  msdos.cpp(2811): note: see usage of 'WM_INPUT'
1>msdos.cpp(2813): error C2065: 'RAWINPUT': undeclared identifier
1>msdos.cpp(2813): error C2146: syntax error: missing ';' before identifier 'ri'
1>msdos.cpp(2813): error C2065: 'ri': undeclared identifier
1>msdos.cpp(2814): error C2065: 'RAWINPUT': undeclared identifier
1>msdos.cpp(2816): error C2065: 'HRAWINPUT': undeclared identifier
1>msdos.cpp(2816): error C2146: syntax error: missing ')' before identifier 'lparam'
1>msdos.cpp(2817): error C2065: 'ri': undeclared identifier
1>msdos.cpp(2817): error C2228: left of '.header' must have class/struct/union
1>  msdos.cpp(2817): note: type is 'unknown-type'
1>msdos.cpp(2817): error C2228: left of '.dwType' must have class/struct/union
1>msdos.cpp(2817): error C2065: 'RIM_TYPEMOUSE': undeclared identifier
1>msdos.cpp(2818): error C2065: 'ri': undeclared identifier
1>msdos.cpp(2818): error C2228: left of '.data' must have class/struct/union
1>  msdos.cpp(2818): note: type is 'unknown-type'
1>msdos.cpp(2818): error C2228: left of '.mouse' must have class/struct/union
1>msdos.cpp(2818): error C2228: left of '.lLastX' must have class/struct/union
1>msdos.cpp(2819): error C2065: 'ri': undeclared identifier
1>msdos.cpp(2819): error C2228: left of '.data' must have class/struct/union
1>  msdos.cpp(2819): note: type is 'unknown-type'
1>msdos.cpp(2819): error C2228: left of '.mouse' must have class/struct/union
1>msdos.cpp(2819): error C2228: left of '.lLastY' must have class/struct/union
1>msdos.cpp(2811): error C2051: case expression not constant

I know I'm not capable of fixing these!

**Comment by cracyc** [comment]
These defines are in winuser.h which should be included so I don't know what's up.  I messed around with trying to get it to build with MSVC 2017 but it's a PITA.  I'd like to know the problems you're seeing with mingw but in the meantime github actions' mingw toolchain builds it without issue.  The artifacts can be found at https://github.com/cracyc/msdos-player/actions by clicking on the newest event.  I don't want to upload the ms copyrighted winhvplatform.h include so the whpx version isn't built currently.

**Comment by emendelson** [comment]
Thank you for this. I'll be able to experiment in the next few days and will report. One question: which MinGW version are you using? The older one with C:\MinGW\msys\1.0, or one of the new varieties?

**Comment by emendelson** [comment]
Because the github action uses msys2, I've been experimenting with msys32; the error I get is this: 

```        -mconsole -static -static-libgcc
In file included from ./msdos.cpp:8:
./msdos.h:23:10: fatal error: mbstring.h: No such file or directory
   23 | #include <mbstring.h>
```

I've added the folders that contain mbstring.h to the PATH (the 32-bit one is msys32\mingw32\i686-w64-mingw32\include) but that clearly isn't enough. My ignorant guess is that I have to set the include paths somewhere, but I can't figure out how to do that (or whether I should be doing it).

Don't waste any time on my ignorance. If the answer isn't obvious in five seconds, don't bother with it!

**Comment by cracyc** [comment]
Try using mingw-w64.  Most projects have switched to it because it's more reliably updated.

**Comment by emendelson** [comment]
I'm going to close this because I'm simply not competent enough to figure out how to use mingw-w64 to build anything, and I don't need to waste anyone's time. Now that I know how to find the artifacts, I don't see any special need to build it... Thank you again for your patience over this!

**Comment by emendelson** [comment]
OK - somehow I figured out the answer to this. To build the latest code in VS2015, all that's needed is to change lines 14 and 15 in msdos.h so that they look like this
```
//#define _WIN32_WINNT 0x500	// Windows 2000 //comment out this line
#define _WIN32_WINNT 0x501	// Windows XP  //  enable this line 
```
Unless you want to build for Win2K, possibly this change might be worth making in the source? That's all that was needed in VS2015. 

**EDIT** Also, with this change, it builds under VS 2019 (and presumably under VS2017 also). All you need to do is update the toolset setting in the properties to the current version.

**Comment by cracyc** [comment]
VS is kind of broken on my computer so I can't update the project settings.  If you do a pull request that'd be helpful.

**Comment by emendelson** [comment]
OK, I hope I've done this correctly - I think it's the first pull request I've created, or at least the first one I can remember.

**Comment by emendelson** [comment]
You can ignore my pull request, because I didn't realize that you were asking for a pull request that updates the toolset in msdos.vcxproj. I don't think there's any reason to change what's in the source, because anyone who tries to build under VS 2015 or later will need to change the setting in the Properties sheet to match whatever they've got on their system. I don't think there's a setting that can work on anyone's system. 

I have mine set to v142, but I expect that other systems will have earlier versions that work equally well.

When I said that "all you need to do is update the toolset setting" I should have made clear that this was necessary in all earlier versions of the code also, not just with the new WINNT setting. Apologies for all confusion!

**Comment by cracyc** [comment]
Since you got it to build, I'll close this.
