### ISSUE TITLE
How to enable mode mono?

### ISSUE THREAD

**Issue by emendelson** [cracyc/msdos-player#7]
This is probably a stupid question, so apologies in advance. I was very glad to see support for MDA in the latest commit. Question: How can I run MODE MONO (or use some 16-bit application that sets video mode 7) before starting an application?

Thanks for any enlightenment, and apologies if this is even more stupid a question than I think.

**Comment by cracyc** [comment]
It'll use it if something sets mode 7.  IMO there's no point in adding a switch because it'll behave just like mode 3.  It's really just a work around for programs which use 0xb0000 for text instead of 0xb8000 and isn't real mda emulation.

**Comment by emendelson** [comment]
OK - thank you!
