### ISSUE TITLE
Upstream has been updated

### ISSUE THREAD

**Issue by emendelson** [cracyc/msdos-player#8]
@cracyc - I just noticed the upstream version of this has been updated:

http://takeda-toshiya.my.coocan.jp/msdos/index.html

If there are any changes that you haven't already made, is there any chance they might be added to your fork? Thank you again for working on this.

**Comment by cracyc** [comment]
I added the fixes but not the new stuff like the np2 cpu emulations.  I'm disinclined to mess with that currently.

**Comment by emendelson** [comment]
Understood! Thank you.
