### ISSUE TITLE
Attribute problem for characters on text screen

### ISSUE THREAD

**Issue by richardFK** [cracyc/msdos-player#9]
It appears that attributes are NOT FULLY supported. For example in the code fragments as below...

mov ah,09h
mov al,58h ;"X" char to display
mov bl,0  ; page 0
mov bl,8eh ; atrribute e = YELLOW    8 = blinking
mov cx,01h
int 10 h ; put YELLOW blinking X at Top Left Hand Corner

push ds
mov ax,0b800h
push ax
pop ds
mov word ptr ds:[0+158],8e58h
pop ds ; put YELLOW blinking X at Top Right Hand Corner

results only with NON-BLINKING YELLOW X's in the correct locations

**Comment by richardFK** [comment]
Just a note - DOSbox does show the X's as BLINKING YELLOW in the correct positions - so I gather that it is possible to achieve with msdos.exe 

I am using Windows 10 x64 Build 20H2 on a INTEL i7 processor

**Comment by cracyc** [comment]
Dosbox draws it's own console while msdos player uses Windows'.  As far as I can tell it doesn't support blink (although the new windows terminal does, https://github.com/microsoft/terminal/commit/d1671a0acd62625b32523f78457b73cd1dc3dc04, as ansi escapes rather than vga text mode attributes.
